workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      android_signing:
        - marketingtool_keystore
      flutter: stable
      vars:
        PACKAGE_NAME: "pro.marketingtool.app"
    scripts:
      - name: Set up local.properties
        script: echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Clean Flutter
        script: flutter clean
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build Release APK
        script: flutter build apk --release
      - name: Build Release App Bundle
        script: flutter build appbundle --release
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - infinity@antiviruspoint.org
        notify:
          success: true
          failure: true

  ios-release:
    name: iOS Release Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: pro.marketingtool.app
      flutter: stable
      vars:
        BUNDLE_ID: "pro.marketingtool.app"
    scripts:
      - name: Set up code signing
        script: xcode-project use-profiles
      - name: Clean Flutter
        script: flutter clean
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
      - name: Build iOS Release
        script: flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
      email:
        recipients:
          - infinity@antiviruspoint.org
        notify:
          success: true
          failure: true
